# ─────────────────────────────────────────────
# Instalar prerequisitos en Amazon Linux 2
# ─────────────────────────────────────────────

- name: Install Node.js 16 from NodeSource on Amazon Linux 2
  shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
  args:
    creates: /etc/yum.repos.d/nodesource*.repo

- name: Install Node.js package on Amazon Linux 2
  yum:
    name: nodejs
    state: present

- name: Install base packages
  yum:
    name:
      - nodejs
      - npm
      - curl
      - unzip
      - git
      - python3
      - python3-pip
      - nc
    state: present

# ─────────────────────────────────────────────
# Validaciones
# ─────────────────────────────────────────────
- name: Validate unzip installation
  command: which unzip
  register: unzip_check
  changed_when: false
  failed_when: unzip_check.rc != 0

- name: Validate Python 3 environment
  command: /usr/bin/python3 -c "import json, os, sys"
  register: python_check
  changed_when: false
  failed_when: python_check.rc != 0
