# # ─────────────────────────────────────────────
# # Wait for SSM Agent to be available on the Instance
# # ─────────────────────────────────────────────
- name: Wait for connection to be available
  hosts: bastion
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ssm-transfer-qa-99009900
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_s3_addressing_style: virtual
  tasks:
    - name: Wait for connection
      wait_for_connection:

# # ─────────────────────────────────────────────
# # Preparar frontend, backend
# # ─────────────────────────────────────────────
- name: Apply common and monitoring roles to all EC2 instances
  hosts: frontend:backend
  become: yes
  gather_facts: false
  roles:
    - common

# # ─────────────────────────────────────────────
# # Configurar backend
# # ─────────────────────────────────────────────
- name: Configure backend application
  hosts: backend
  become: yes
  gather_facts: false
  roles:
    - backend

# ─────────────────────────────────────────────
# Configurar frontend
# ─────────────────────────────────────────────
- name: Configure frontend application
  hosts: frontend
  become: yes
  gather_facts: false
  roles:
    - frontend
